### ISSUE TITLE
Is a production grade React app feasible without redux?

### ISSUE THREAD

**Issue by jasan-s** [vkammerer/react-redux-firebase#1]
this is more of a question than a issue. Im a react newbie and through research have decided to use firebase as backend for a MVP for an app. I m wondering, as to if i really need to use redux, or can i just get away with firebase and react. You seemed to use firebase + redux in this sample react app. Can you point out why one would need to use redux/flux for that matter to make an react app if one is using firebase as a backend. Thanks in advance

**Comment by vkammerer** [comment]
The advantage of Redux in this particular stack is that it makes it easy to bind the state of your local React application to the data from / to Firebase. As you can see in the files located in the ./src/actions folder, it is quite simple (and legible) to keep the local state of our application in sync with the data in the cloud.
But you can do without redux if you like, especially if your application is simple, by binding yourself your components states to calls to the Firebase methods.
